/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_HW_CORE_GENERATED_TRACERS_H
#define TRACE_HW_CORE_GENERATED_TRACERS_H

#include "trace/control.h"

extern TraceEvent _TRACE_LOADER_WRITE_ROM_EVENT;
extern uint16_t _TRACE_LOADER_WRITE_ROM_DSTATE;
#define TRACE_LOADER_WRITE_ROM_ENABLED 1
#include "qemu/log-for-trace.h"


#define TRACE_LOADER_WRITE_ROM_BACKEND_DSTATE() ( \
    trace_event_get_state_dynamic_by_id(TRACE_LOADER_WRITE_ROM) || \
    false)

static inline void _nocheck__trace_loader_write_rom(const char * name, uint64_t gpa, uint64_t size, bool isrom)
{
    if (trace_event_get_state(TRACE_LOADER_WRITE_ROM) && qemu_loglevel_mask(LOG_TRACE)) {
        struct timeval _now;
        gettimeofday(&_now, NULL);
        qemu_log("%d@%zu.%06zu:loader_write_rom " "%s: @0x%"PRIx64" size=0x%"PRIx64" ROM=%d" "\n",
                 qemu_get_thread_id(),
                 (size_t)_now.tv_sec, (size_t)_now.tv_usec
                 , name, gpa, size, isrom);
    }
}

static inline void trace_loader_write_rom(const char * name, uint64_t gpa, uint64_t size, bool isrom)
{
    if (true) {
        _nocheck__trace_loader_write_rom(name, gpa, size, isrom);
    }
}
#endif /* TRACE_HW_CORE_GENERATED_TRACERS_H */
