################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/no/qapi/opts-visitor.c \
../src/no/qapi/qapi-builtin-types.c \
../src/no/qapi/qapi-builtin-visit.c \
../src/no/qapi/qapi-clone-visitor.c \
../src/no/qapi/qapi-dealloc-visitor.c \
../src/no/qapi/qapi-emit-events.c \
../src/no/qapi/qapi-events-audio.c \
../src/no/qapi/qapi-events-authz.c \
../src/no/qapi/qapi-events-block-core.c \
../src/no/qapi/qapi-events-block.c \
../src/no/qapi/qapi-events-char.c \
../src/no/qapi/qapi-events-common.c \
../src/no/qapi/qapi-events-crypto.c \
../src/no/qapi/qapi-events-dump.c \
../src/no/qapi/qapi-events-error.c \
../src/no/qapi/qapi-events-introspect.c \
../src/no/qapi/qapi-events-job.c \
../src/no/qapi/qapi-events-machine.c \
../src/no/qapi/qapi-events-migration.c \
../src/no/qapi/qapi-events-misc.c \
../src/no/qapi/qapi-events-net.c \
../src/no/qapi/qapi-events-qdev.c \
../src/no/qapi/qapi-events-qom.c \
../src/no/qapi/qapi-events-rdma.c \
../src/no/qapi/qapi-events-rocker.c \
../src/no/qapi/qapi-events-run-state.c \
../src/no/qapi/qapi-events-sockets.c \
../src/no/qapi/qapi-events-tpm.c \
../src/no/qapi/qapi-events-trace.c \
../src/no/qapi/qapi-events-transaction.c \
../src/no/qapi/qapi-events-ui.c \
../src/no/qapi/qapi-types-audio.c \
../src/no/qapi/qapi-types-authz.c \
../src/no/qapi/qapi-types-block-core.c \
../src/no/qapi/qapi-types-block.c \
../src/no/qapi/qapi-types-char.c \
../src/no/qapi/qapi-types-common.c \
../src/no/qapi/qapi-types-crypto.c \
../src/no/qapi/qapi-types-dump.c \
../src/no/qapi/qapi-types-error.c \
../src/no/qapi/qapi-types-introspect.c \
../src/no/qapi/qapi-types-job.c \
../src/no/qapi/qapi-types-machine.c \
../src/no/qapi/qapi-types-migration.c \
../src/no/qapi/qapi-types-misc.c \
../src/no/qapi/qapi-types-net.c \
../src/no/qapi/qapi-types-qdev.c \
../src/no/qapi/qapi-types-qom.c \
../src/no/qapi/qapi-types-rdma.c \
../src/no/qapi/qapi-types-rocker.c \
../src/no/qapi/qapi-types-run-state.c \
../src/no/qapi/qapi-types-sockets.c \
../src/no/qapi/qapi-types-tpm.c \
../src/no/qapi/qapi-types-trace.c \
../src/no/qapi/qapi-types-transaction.c \
../src/no/qapi/qapi-types-ui.c \
../src/no/qapi/qapi-util.c \
../src/no/qapi/qapi-visit-audio.c \
../src/no/qapi/qapi-visit-authz.c \
../src/no/qapi/qapi-visit-block-core.c \
../src/no/qapi/qapi-visit-block.c \
../src/no/qapi/qapi-visit-char.c \
../src/no/qapi/qapi-visit-common.c \
../src/no/qapi/qapi-visit-core.c \
../src/no/qapi/qapi-visit-crypto.c \
../src/no/qapi/qapi-visit-dump.c \
../src/no/qapi/qapi-visit-error.c \
../src/no/qapi/qapi-visit-introspect.c \
../src/no/qapi/qapi-visit-job.c \
../src/no/qapi/qapi-visit-machine.c \
../src/no/qapi/qapi-visit-migration.c \
../src/no/qapi/qapi-visit-misc.c \
../src/no/qapi/qapi-visit-net.c \
../src/no/qapi/qapi-visit-qdev.c \
../src/no/qapi/qapi-visit-qom.c \
../src/no/qapi/qapi-visit-rdma.c \
../src/no/qapi/qapi-visit-rocker.c \
../src/no/qapi/qapi-visit-run-state.c \
../src/no/qapi/qapi-visit-sockets.c \
../src/no/qapi/qapi-visit-tpm.c \
../src/no/qapi/qapi-visit-trace.c \
../src/no/qapi/qapi-visit-transaction.c \
../src/no/qapi/qapi-visit-ui.c \
../src/no/qapi/qmp-dispatch.c \
../src/no/qapi/qmp-event.c \
../src/no/qapi/qmp-registry.c \
../src/no/qapi/qobject-input-visitor.c \
../src/no/qapi/qobject-output-visitor.c \
../src/no/qapi/string-input-visitor.c \
../src/no/qapi/string-output-visitor.c \
../src/no/qapi/trace.c 

OBJS += \
./src/no/qapi/opts-visitor.o \
./src/no/qapi/qapi-builtin-types.o \
./src/no/qapi/qapi-builtin-visit.o \
./src/no/qapi/qapi-clone-visitor.o \
./src/no/qapi/qapi-dealloc-visitor.o \
./src/no/qapi/qapi-emit-events.o \
./src/no/qapi/qapi-events-audio.o \
./src/no/qapi/qapi-events-authz.o \
./src/no/qapi/qapi-events-block-core.o \
./src/no/qapi/qapi-events-block.o \
./src/no/qapi/qapi-events-char.o \
./src/no/qapi/qapi-events-common.o \
./src/no/qapi/qapi-events-crypto.o \
./src/no/qapi/qapi-events-dump.o \
./src/no/qapi/qapi-events-error.o \
./src/no/qapi/qapi-events-introspect.o \
./src/no/qapi/qapi-events-job.o \
./src/no/qapi/qapi-events-machine.o \
./src/no/qapi/qapi-events-migration.o \
./src/no/qapi/qapi-events-misc.o \
./src/no/qapi/qapi-events-net.o \
./src/no/qapi/qapi-events-qdev.o \
./src/no/qapi/qapi-events-qom.o \
./src/no/qapi/qapi-events-rdma.o \
./src/no/qapi/qapi-events-rocker.o \
./src/no/qapi/qapi-events-run-state.o \
./src/no/qapi/qapi-events-sockets.o \
./src/no/qapi/qapi-events-tpm.o \
./src/no/qapi/qapi-events-trace.o \
./src/no/qapi/qapi-events-transaction.o \
./src/no/qapi/qapi-events-ui.o \
./src/no/qapi/qapi-types-audio.o \
./src/no/qapi/qapi-types-authz.o \
./src/no/qapi/qapi-types-block-core.o \
./src/no/qapi/qapi-types-block.o \
./src/no/qapi/qapi-types-char.o \
./src/no/qapi/qapi-types-common.o \
./src/no/qapi/qapi-types-crypto.o \
./src/no/qapi/qapi-types-dump.o \
./src/no/qapi/qapi-types-error.o \
./src/no/qapi/qapi-types-introspect.o \
./src/no/qapi/qapi-types-job.o \
./src/no/qapi/qapi-types-machine.o \
./src/no/qapi/qapi-types-migration.o \
./src/no/qapi/qapi-types-misc.o \
./src/no/qapi/qapi-types-net.o \
./src/no/qapi/qapi-types-qdev.o \
./src/no/qapi/qapi-types-qom.o \
./src/no/qapi/qapi-types-rdma.o \
./src/no/qapi/qapi-types-rocker.o \
./src/no/qapi/qapi-types-run-state.o \
./src/no/qapi/qapi-types-sockets.o \
./src/no/qapi/qapi-types-tpm.o \
./src/no/qapi/qapi-types-trace.o \
./src/no/qapi/qapi-types-transaction.o \
./src/no/qapi/qapi-types-ui.o \
./src/no/qapi/qapi-util.o \
./src/no/qapi/qapi-visit-audio.o \
./src/no/qapi/qapi-visit-authz.o \
./src/no/qapi/qapi-visit-block-core.o \
./src/no/qapi/qapi-visit-block.o \
./src/no/qapi/qapi-visit-char.o \
./src/no/qapi/qapi-visit-common.o \
./src/no/qapi/qapi-visit-core.o \
./src/no/qapi/qapi-visit-crypto.o \
./src/no/qapi/qapi-visit-dump.o \
./src/no/qapi/qapi-visit-error.o \
./src/no/qapi/qapi-visit-introspect.o \
./src/no/qapi/qapi-visit-job.o \
./src/no/qapi/qapi-visit-machine.o \
./src/no/qapi/qapi-visit-migration.o \
./src/no/qapi/qapi-visit-misc.o \
./src/no/qapi/qapi-visit-net.o \
./src/no/qapi/qapi-visit-qdev.o \
./src/no/qapi/qapi-visit-qom.o \
./src/no/qapi/qapi-visit-rdma.o \
./src/no/qapi/qapi-visit-rocker.o \
./src/no/qapi/qapi-visit-run-state.o \
./src/no/qapi/qapi-visit-sockets.o \
./src/no/qapi/qapi-visit-tpm.o \
./src/no/qapi/qapi-visit-trace.o \
./src/no/qapi/qapi-visit-transaction.o \
./src/no/qapi/qapi-visit-ui.o \
./src/no/qapi/qmp-dispatch.o \
./src/no/qapi/qmp-event.o \
./src/no/qapi/qmp-registry.o \
./src/no/qapi/qobject-input-visitor.o \
./src/no/qapi/qobject-output-visitor.o \
./src/no/qapi/string-input-visitor.o \
./src/no/qapi/string-output-visitor.o \
./src/no/qapi/trace.o 

C_DEPS += \
./src/no/qapi/opts-visitor.d \
./src/no/qapi/qapi-builtin-types.d \
./src/no/qapi/qapi-builtin-visit.d \
./src/no/qapi/qapi-clone-visitor.d \
./src/no/qapi/qapi-dealloc-visitor.d \
./src/no/qapi/qapi-emit-events.d \
./src/no/qapi/qapi-events-audio.d \
./src/no/qapi/qapi-events-authz.d \
./src/no/qapi/qapi-events-block-core.d \
./src/no/qapi/qapi-events-block.d \
./src/no/qapi/qapi-events-char.d \
./src/no/qapi/qapi-events-common.d \
./src/no/qapi/qapi-events-crypto.d \
./src/no/qapi/qapi-events-dump.d \
./src/no/qapi/qapi-events-error.d \
./src/no/qapi/qapi-events-introspect.d \
./src/no/qapi/qapi-events-job.d \
./src/no/qapi/qapi-events-machine.d \
./src/no/qapi/qapi-events-migration.d \
./src/no/qapi/qapi-events-misc.d \
./src/no/qapi/qapi-events-net.d \
./src/no/qapi/qapi-events-qdev.d \
./src/no/qapi/qapi-events-qom.d \
./src/no/qapi/qapi-events-rdma.d \
./src/no/qapi/qapi-events-rocker.d \
./src/no/qapi/qapi-events-run-state.d \
./src/no/qapi/qapi-events-sockets.d \
./src/no/qapi/qapi-events-tpm.d \
./src/no/qapi/qapi-events-trace.d \
./src/no/qapi/qapi-events-transaction.d \
./src/no/qapi/qapi-events-ui.d \
./src/no/qapi/qapi-types-audio.d \
./src/no/qapi/qapi-types-authz.d \
./src/no/qapi/qapi-types-block-core.d \
./src/no/qapi/qapi-types-block.d \
./src/no/qapi/qapi-types-char.d \
./src/no/qapi/qapi-types-common.d \
./src/no/qapi/qapi-types-crypto.d \
./src/no/qapi/qapi-types-dump.d \
./src/no/qapi/qapi-types-error.d \
./src/no/qapi/qapi-types-introspect.d \
./src/no/qapi/qapi-types-job.d \
./src/no/qapi/qapi-types-machine.d \
./src/no/qapi/qapi-types-migration.d \
./src/no/qapi/qapi-types-misc.d \
./src/no/qapi/qapi-types-net.d \
./src/no/qapi/qapi-types-qdev.d \
./src/no/qapi/qapi-types-qom.d \
./src/no/qapi/qapi-types-rdma.d \
./src/no/qapi/qapi-types-rocker.d \
./src/no/qapi/qapi-types-run-state.d \
./src/no/qapi/qapi-types-sockets.d \
./src/no/qapi/qapi-types-tpm.d \
./src/no/qapi/qapi-types-trace.d \
./src/no/qapi/qapi-types-transaction.d \
./src/no/qapi/qapi-types-ui.d \
./src/no/qapi/qapi-util.d \
./src/no/qapi/qapi-visit-audio.d \
./src/no/qapi/qapi-visit-authz.d \
./src/no/qapi/qapi-visit-block-core.d \
./src/no/qapi/qapi-visit-block.d \
./src/no/qapi/qapi-visit-char.d \
./src/no/qapi/qapi-visit-common.d \
./src/no/qapi/qapi-visit-core.d \
./src/no/qapi/qapi-visit-crypto.d \
./src/no/qapi/qapi-visit-dump.d \
./src/no/qapi/qapi-visit-error.d \
./src/no/qapi/qapi-visit-introspect.d \
./src/no/qapi/qapi-visit-job.d \
./src/no/qapi/qapi-visit-machine.d \
./src/no/qapi/qapi-visit-migration.d \
./src/no/qapi/qapi-visit-misc.d \
./src/no/qapi/qapi-visit-net.d \
./src/no/qapi/qapi-visit-qdev.d \
./src/no/qapi/qapi-visit-qom.d \
./src/no/qapi/qapi-visit-rdma.d \
./src/no/qapi/qapi-visit-rocker.d \
./src/no/qapi/qapi-visit-run-state.d \
./src/no/qapi/qapi-visit-sockets.d \
./src/no/qapi/qapi-visit-tpm.d \
./src/no/qapi/qapi-visit-trace.d \
./src/no/qapi/qapi-visit-transaction.d \
./src/no/qapi/qapi-visit-ui.d \
./src/no/qapi/qmp-dispatch.d \
./src/no/qapi/qmp-event.d \
./src/no/qapi/qmp-registry.d \
./src/no/qapi/qobject-input-visitor.d \
./src/no/qapi/qobject-output-visitor.d \
./src/no/qapi/string-input-visitor.d \
./src/no/qapi/string-output-visitor.d \
./src/no/qapi/trace.d 


# Each subdirectory must supply rules for building sources it contributes
src/no/qapi/%.o: ../src/no/qapi/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -D_FORTIFY_SOURCE=2 -D_LARGEFILE_SOURCE=1 -D_GNU_SOURCE=1 -DPIE=1 -DFILE_OFFSET_BITS=64 -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/accel" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/accel/tcg" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/block/dataplane" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/vfio" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/riscv" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/target/riscv" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/trace" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/linux-headers" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/stubs" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/acpi" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/audio" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/block" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/char" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/core" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/display" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/i2c" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/ide" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/input" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/intc" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/misc" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/net" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/nvram" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/pci-host" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/pci" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/scsi" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/sd" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/timer" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/tpm" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/usb" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no" -I/usr/include/libusb-1.0 -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/virtio" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/hw/watchdog" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/migration" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/monitor" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/net" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/audio" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/ui" -I/usr/include/SDL2 -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/qom" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/authz" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/qapi" -I/usr/include/libxml2 -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/nbd" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/scsi" -I/usr/include/x86_64-linux-gnu -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/block" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/chardev" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/crypto" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/io" -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/include/pixman-1 -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no/include" -I"/home/steve/code/work/qemu420/system/src/libqemuutil.a/src/no" -O0 -g -Wall -c -fmessage-length=0 -fPIC -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


