################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
CC_DEPS := 
C++_DEPS := 
EXECUTABLES := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/no/accel \
src/no/accel/kvm \
src/no/accel/stubs \
src/no/accel/tcg \
src/no \
src/no/arm-softmmu \
src/no/arm-softmmu/trace \
src/no/audio \
src/no/authz \
src/no/backends \
src/no/block \
src/no/chardev \
src/no/crypto \
src/no/disas \
src/no/disas/libvixl/vixl/a64 \
src/no/disas/libvixl/vixl \
src/no/dump \
src/no/fpu \
src/no/fsdev \
src/no/hw/9pfs \
src/no/hw/acpi \
src/no/hw/adc \
src/no/hw/arm \
src/no/hw/audio \
src/no/hw/block \
src/no/hw/block/dataplane \
src/no/hw/bt \
src/no/hw/char \
src/no/hw/core \
src/no/hw/cpu \
src/no/hw/display \
src/no/hw/dma \
src/no/hw/gpio \
src/no/hw/i2c \
src/no/hw/ide \
src/no/hw/input \
src/no/hw/intc \
src/no/hw/ipack \
src/no/hw/mem \
src/no/hw/misc \
src/no/hw/net \
src/no/hw/net/can \
src/no/hw/net/rocker \
src/no/hw/nvram \
src/no/hw/pci \
src/no/hw/pci-bridge \
src/no/hw/pci-host \
src/no/hw/pcmcia \
src/no/hw/rtc \
src/no/hw/scsi \
src/no/hw/sd \
src/no/hw/semihosting \
src/no/hw/smbios \
src/no/hw/ssi \
src/no/hw/timer \
src/no/hw/tpm \
src/no/hw/usb \
src/no/hw/vfio \
src/no/hw/virtio \
src/no/hw/watchdog \
src/no/io \
src/no/migration \
src/no/monitor \
src/no/nbd \
src/no/net \
src/no/net/can \
src/no/qapi \
src/no/qom \
src/no/replay \
src/no/scsi \
src/no/target/arm \
src/no/tcg \
src/no/trace \
src/no/ui \

