################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_UPPER_SRCS := 
CXX_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
CC_SRCS := 
ASM_SRCS := 
CPP_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
LIBRARIES := 
CC_DEPS := 
C++_DEPS := 
C_UPPER_DEPS := 
CXX_DEPS := 
OBJS := 
CPP_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/no/accel/kvm \
src/no/accel/tcg \
src/no/audio \
src/no/authz \
src/no/block \
src/no/chardev \
src/no/crypto \
src/no/hw/9pfs \
src/no/hw/acpi \
src/no/hw/alpha \
src/no/hw/arm \
src/no/hw/audio \
src/no/hw/block/dataplane \
src/no/hw/block \
src/no/hw/char \
src/no/hw/core \
src/no/hw/display \
src/no/hw/dma \
src/no/hw/gpio \
src/no/hw/hppa \
src/no/hw/i2c \
src/no/hw/i386 \
src/no/hw/i386/xen \
src/no/hw/ide \
src/no/hw/input \
src/no/hw/intc \
src/no/hw/isa \
src/no/hw/mem \
src/no/hw/mips \
src/no/hw/misc/macio \
src/no/hw/misc \
src/no/hw/net \
src/no/hw/nvram \
src/no/hw/pci \
src/no/hw/pci-host \
src/no/hw/ppc \
src/no/hw/rdma \
src/no/hw/rdma/vmw \
src/no/hw/riscv \
src/no/hw/rtc \
src/no/hw/s390x \
src/no/hw/scsi \
src/no/hw/sd \
src/no/hw/sparc \
src/no/hw/sparc64 \
src/no/hw/timer \
src/no/hw/tpm \
src/no/hw/usb \
src/no/hw/vfio \
src/no/hw/virtio \
src/no/hw/watchdog \
src/no/hw/xen \
src/no/io \
src/no/migration \
src/no/monitor \
src/no/nbd \
src/no/net \
src/no/qapi \
src/no/qobject \
src/no/qom \
src/no/scsi \
src/no/stubs \
src/no/target/arm \
src/no/target/hppa \
src/no/target/i386 \
src/no/target/mips \
src/no/target/ppc \
src/no/target/riscv \
src/no/target/s390x \
src/no/target/sparc \
src/no/trace \
src/no \
src/no/ui \
src/no/util \

