#Auto generated by Edalize

TOP_MODULE        := ibex_simple_system
VC_FILE           := lowrisc_ibex_ibex_simple_system_0.vc
VERILATOR_OPTIONS := --trace --trace-fst --trace-structs --trace-params --trace-max-array 1024 -CFLAGS "-std=c++11 -Wall -DVM_TRACE_FMT_FST -DTOPLEVEL_NAME=ibex_simple_system -g" -LDFLAGS "-pthread -lutil -lelf" -Wall -Wwarn-IMPERFECTSCH --unroll-count 72
MAKE_OPTIONS      := 
