// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Primary design header
//
// This header should be included by all source files instantiating the design.
// The class here is then constructed to instantiate the design.
// See the Verilator manual for examples.

#ifndef _VIBEX_SIMPLE_SYSTEM_H_
#define _VIBEX_SIMPLE_SYSTEM_H_  // guard

#include "verilated_heavy.h"
#include "Vibex_simple_system__Dpi.h"

//==========

class Vibex_simple_system__Syms;
class Vibex_simple_system_VerilatedFst;


//----------

VL_MODULE(Vibex_simple_system) {
  public:
    
    // PORTS
    // The application code writes and reads these signals to
    // propagate new values into/out from the Verilated model.
    VL_IN8(IO_RST_N,0,0);
    VL_IN8(IO_CLK,0,0);
    
    // LOCAL SIGNALS
    // Internals; generally not touched by application code
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ ibex_simple_system__clk_sys;
        CData/*0:0*/ ibex_core_clk;
        CData/*0:0*/ ibex_simple_system__instr_req;
        CData/*0:0*/ ibex_simple_system__instr_rvalid;
        CData/*0:0*/ ibex_bus_host_sel_req;
        CData/*0:0*/ ibex_bus_host_sel_resp;
        CData/*1:0*/ ibex_bus_device_sel_req;
        CData/*1:0*/ ibex_bus_device_sel_resp;
        CData/*0:0*/ ibex_core_instr_is_compressed_id;
        CData/*0:0*/ ibex_core_instr_fetch_err;
        CData/*0:0*/ ibex_core_instr_fetch_err_plus2;
        CData/*0:0*/ ibex_core_illegal_c_insn_id;
        CData/*1:0*/ ibex_core_imd_val_we_ex;
        CData/*0:0*/ ibex_core_icache_inval;
        CData/*0:0*/ ibex_core_instr_valid_clear;
        CData/*0:0*/ ibex_core_pc_set;
        CData/*0:0*/ ibex_core_pc_set_spec;
        CData/*2:0*/ ibex_core_pc_mux_id;
        CData/*1:0*/ ibex_core_exc_pc_mux_id;
        CData/*5:0*/ ibex_core_exc_cause;
        CData/*0:0*/ ibex_core_lsu_load_err;
        CData/*0:0*/ ibex_core_lsu_store_err;
        CData/*0:0*/ ibex_core_lsu_addr_incr_req;
        CData/*0:0*/ ibex_core_ctrl_busy;
        CData/*0:0*/ ibex_core_core_busy_q;
        CData/*0:0*/ ibex_core_rf_we_lsu;
        CData/*0:0*/ ibex_core_mult_sel_ex;
        CData/*0:0*/ ibex_core_div_sel_ex;
        CData/*0:0*/ ibex_core_csr_access;
        CData/*1:0*/ ibex_core_csr_op;
        CData/*0:0*/ ibex_core_csr_op_en;
        CData/*0:0*/ ibex_core_illegal_csr_insn_id;
        CData/*0:0*/ ibex_core_id_in_ready;
        CData/*0:0*/ ibex_core_ex_valid;
        CData/*0:0*/ ibex_core_lsu_resp_valid;
        CData/*0:0*/ ibex_core_instr_req_int;
        CData/*0:0*/ ibex_core_data_req_out;
        CData/*0:0*/ ibex_core_csr_save_if;
        CData/*0:0*/ ibex_core_csr_save_id;
        CData/*0:0*/ ibex_core_csr_restore_mret_id;
        CData/*0:0*/ ibex_core_csr_restore_dret_id;
        CData/*0:0*/ ibex_core_csr_save_cause;
        CData/*0:0*/ ibex_core_csr_mtvec_init;
        CData/*2:0*/ ibex_core_debug_cause;
        CData/*0:0*/ ibex_core_debug_csr_save;
        CData/*0:0*/ ibex_core_perf_instr_ret_wb;
        CData/*0:0*/ ibex_core_perf_jump;
        CData/*0:0*/ ibex_core_perf_branch;
        CData/*0:0*/ ibex_core_perf_tbranch;
        CData/*0:0*/ ibex_core_perf_load;
        CData/*0:0*/ ibex_core_perf_store;
        CData/*0:0*/ ibex_core_illegal_insn_id;
        CData/*0:0*/ ibex_core_rvfi_intr_d;
        CData/*0:0*/ ibex_core_rvfi_intr_q;
        CData/*0:0*/ ibex_core_rvfi_set_trap_pc_d;
        CData/*0:0*/ ibex_core_rvfi_set_trap_pc_q;
        CData/*4:0*/ ibex_core_rvfi_rs1_addr_d;
        CData/*4:0*/ ibex_core_rvfi_rs1_addr_q;
        CData/*4:0*/ ibex_core_rvfi_rs2_addr_d;
        CData/*4:0*/ ibex_core_rvfi_rs2_addr_q;
        CData/*4:0*/ ibex_core_rvfi_rd_addr_q;
        CData/*4:0*/ ibex_core_rvfi_rd_addr_d;
        CData/*0:0*/ ibex_core_rvfi_rd_we_wb;
        CData/*3:0*/ ibex_core_rvfi_mem_mask_int;
    };
    struct {
        CData/*0:0*/ ibex_core_fetch_enable_q;
        CData/*0:0*/ ibex_core_core_clock_gate_i_gen_generic__u_impl_generic__en_latch;
        CData/*0:0*/ ibex_core_if_stage_i_instr_valid_id_d;
        CData/*0:0*/ ibex_core_if_stage_i_instr_valid_id_q;
        CData/*0:0*/ ibex_core_if_stage_i_instr_new_id_d;
        CData/*0:0*/ ibex_core_if_stage_i_instr_new_id_q;
        CData/*0:0*/ ibex_core_if_stage_i_fetch_err;
        CData/*0:0*/ ibex_core_if_stage_i_illegal_c_insn;
        CData/*0:0*/ ibex_core_pre_buf_i_valid_new_req;
        CData/*0:0*/ ibex_core_pre_buf_i_valid_req;
        CData/*0:0*/ ibex_core_pre_buf_i_valid_req_q;
        CData/*0:0*/ ibex_core_pre_buf_i_discard_req_d;
        CData/*0:0*/ ibex_core_pre_buf_i_discard_req_q;
        CData/*0:0*/ ibex_core_pre_buf_i_gnt_or_pmp_err;
        CData/*0:0*/ ibex_core_pre_buf_i_rvalid_or_pmp_err;
        CData/*1:0*/ ibex_core_pre_buf_i_rdata_outstanding_n;
        CData/*1:0*/ ibex_core_pre_buf_i_rdata_outstanding_q;
        CData/*1:0*/ ibex_core_pre_buf_i_branch_discard_n;
        CData/*1:0*/ ibex_core_pre_buf_i_branch_discard_q;
        CData/*1:0*/ ibex_core_pre_buf_i_rdata_pmp_err_n;
        CData/*1:0*/ ibex_core_pre_buf_i_rdata_pmp_err_q;
        CData/*1:0*/ ibex_core_pre_buf_i_rdata_outstanding_rev;
        CData/*0:0*/ ibex_core_pre_buf_i_fifo_valid;
        CData/*0:0*/ ibex_core_pre_buf_i_valid_raw;
        CData/*2:0*/ ibex_core_pre_buf_i_fifo_i_err_d;
        CData/*2:0*/ ibex_core_pre_buf_i_fifo_i_err_q;
        CData/*2:0*/ ibex_core_pre_buf_i_fifo_i_valid_d;
        CData/*2:0*/ ibex_core_pre_buf_i_fifo_i_valid_q;
        CData/*2:0*/ ibex_core_pre_buf_i_fifo_i_lowest_free_entry;
        CData/*2:0*/ ibex_core_pre_buf_i_fifo_i_valid_pushed;
        CData/*2:0*/ ibex_core_pre_buf_i_fifo_i_valid_popped;
        CData/*2:0*/ ibex_core_pre_buf_i_fifo_i_entry_en;
        CData/*0:0*/ ibex_core_pre_buf_i_fifo_i_pop_fifo;
        CData/*0:0*/ ibex_core_pre_buf_i_fifo_i_err;
        CData/*0:0*/ ibex_core_pre_buf_i_fifo_i_valid;
        CData/*0:0*/ ibex_core_pre_buf_i_fifo_i_aligned_is_compressed;
        CData/*0:0*/ ibex_core_pre_buf_i_fifo_i_unaligned_is_compressed;
        CData/*0:0*/ ibex_core_pre_buf_i_fifo_i_addr_incr_two;
        CData/*0:0*/ ibex_core_id_stage_i_ebrk_insn;
        CData/*0:0*/ ibex_core_id_stage_i_mret_insn_dec;
        CData/*0:0*/ ibex_core_id_stage_i_dret_insn_dec;
        CData/*0:0*/ ibex_core_id_stage_i_ecall_insn_dec;
        CData/*0:0*/ ibex_core_id_stage_i_wfi_insn_dec;
        CData/*0:0*/ ibex_core_id_stage_i_branch_in_dec;
        CData/*0:0*/ ibex_core_id_stage_i_branch_spec;
        CData/*0:0*/ ibex_core_id_stage_i_branch_set;
        CData/*0:0*/ ibex_core_id_stage_i_branch_set_raw_d;
        CData/*0:0*/ ibex_core_id_stage_i_branch_jump_set_done_q;
        CData/*0:0*/ ibex_core_id_stage_i_branch_jump_set_done_d;
        CData/*0:0*/ ibex_core_id_stage_i_jump_in_dec;
        CData/*0:0*/ ibex_core_id_stage_i_jump_set_dec;
        CData/*0:0*/ ibex_core_id_stage_i_jump_set;
        CData/*0:0*/ ibex_core_id_stage_i_jump_set_raw;
        CData/*0:0*/ ibex_core_id_stage_i_instr_first_cycle;
        CData/*0:0*/ ibex_core_id_stage_i_instr_executing_spec;
        CData/*0:0*/ ibex_core_id_stage_i_instr_done;
        CData/*0:0*/ ibex_core_id_stage_i_controller_run;
        CData/*0:0*/ ibex_core_id_stage_i_stall_multdiv;
        CData/*0:0*/ ibex_core_id_stage_i_stall_branch;
        CData/*0:0*/ ibex_core_id_stage_i_stall_jump;
        CData/*0:0*/ ibex_core_id_stage_i_stall_id;
        CData/*0:0*/ ibex_core_id_stage_i_multicycle_done;
        CData/*0:0*/ ibex_core_id_stage_i_rf_wdata_sel;
        CData/*0:0*/ ibex_core_id_stage_i_rf_we_raw;
    };
    struct {
        CData/*0:0*/ ibex_core_id_stage_i_rf_ren_a;
        CData/*0:0*/ ibex_core_id_stage_i_rf_ren_b;
        CData/*5:0*/ ibex_core_id_stage_i_alu_operator;
        CData/*1:0*/ ibex_core_id_stage_i_alu_op_a_mux_sel;
        CData/*1:0*/ ibex_core_id_stage_i_alu_op_a_mux_sel_dec;
        CData/*0:0*/ ibex_core_id_stage_i_alu_op_b_mux_sel_dec;
        CData/*0:0*/ ibex_core_id_stage_i_stall_alu;
        CData/*0:0*/ ibex_core_id_stage_i_imm_a_mux_sel;
        CData/*2:0*/ ibex_core_id_stage_i_imm_b_mux_sel;
        CData/*2:0*/ ibex_core_id_stage_i_imm_b_mux_sel_dec;
        CData/*0:0*/ ibex_core_id_stage_i_mult_en_dec;
        CData/*0:0*/ ibex_core_id_stage_i_div_en_dec;
        CData/*0:0*/ ibex_core_id_stage_i_multdiv_en_dec;
        CData/*1:0*/ ibex_core_id_stage_i_multdiv_operator;
        CData/*1:0*/ ibex_core_id_stage_i_multdiv_signed_mode;
        CData/*0:0*/ ibex_core_id_stage_i_lsu_we;
        CData/*1:0*/ ibex_core_id_stage_i_lsu_type;
        CData/*0:0*/ ibex_core_id_stage_i_lsu_sign_ext;
        CData/*0:0*/ ibex_core_id_stage_i_lsu_req;
        CData/*0:0*/ ibex_core_id_stage_i_lsu_req_dec;
        CData/*0:0*/ ibex_core_id_stage_i_csr_pipe_flush;
        CData/*0:0*/ ibex_core_id_stage_i_id_fsm_q;
        CData/*0:0*/ ibex_core_id_stage_i_id_fsm_d;
        CData/*0:0*/ ibex_core_id_stage_i_g_branch_set_flop__branch_set_raw_q;
        CData/*0:0*/ ibex_core_id_stage_i_decoder_i_illegal_insn;
        CData/*0:0*/ ibex_core_id_stage_i_decoder_i_csr_illegal;
        CData/*0:0*/ ibex_core_id_stage_i_decoder_i_rf_we;
        CData/*1:0*/ ibex_core_id_stage_i_decoder_i_csr_op;
        CData/*6:0*/ ibex_core_id_stage_i_decoder_i_opcode;
        CData/*6:0*/ ibex_core_id_stage_i_decoder_i_opcode_alu;
        CData/*3:0*/ ibex_core_id_stage_i_controller_i_ctrl_fsm_cs;
        CData/*3:0*/ ibex_core_id_stage_i_controller_i_ctrl_fsm_ns;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_nmi_mode_q;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_nmi_mode_d;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_debug_mode_q;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_debug_mode_d;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_load_err_q;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_store_err_q;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_exc_req_q;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_exc_req_d;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_illegal_insn_q;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_illegal_insn_d;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_instr_fetch_err_prio;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_illegal_insn_prio;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_ecall_insn_prio;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_ebrk_insn_prio;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_store_err_prio;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_load_err_prio;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_halt_if;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_retain_id;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_flush_id;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_special_req;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_enter_debug_mode_d;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_enter_debug_mode_q;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_ebreak_into_debug;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_handle_irq;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_ecall_insn;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_mret_insn;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_dret_insn;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_wfi_insn;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_ebrk_insn;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_csr_pipe_flush;
        CData/*0:0*/ ibex_core_id_stage_i_controller_i_instr_fetch_err;
        CData/*0:0*/ ibex_core_ex_block_i_multdiv_sel;
    };
    struct {
        CData/*1:0*/ ibex_core_ex_block_i_multdiv_imd_val_we;
        CData/*0:0*/ ibex_core_ex_block_i_alu_i_adder_op_b_negate;
        CData/*0:0*/ ibex_core_ex_block_i_alu_i_cmp_signed;
        CData/*0:0*/ ibex_core_ex_block_i_alu_i_cmp_result;
        CData/*0:0*/ ibex_core_ex_block_i_alu_i_shift_left;
        CData/*5:0*/ ibex_core_ex_block_i_alu_i_shift_amt;
        CData/*0:0*/ ibex_core_ex_block_i_alu_i_unused_shift_result_ext;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_sign_a;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_sign_b;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_mult_valid;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_div_sign_a;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_div_sign_b;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_is_greater_equal;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_div_valid;
        CData/*4:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_div_counter_q;
        CData/*4:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_div_counter_d;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_mult_hold;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_div_hold;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_div_by_zero_d;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_div_by_zero_q;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_mult_en_internal;
        CData/*0:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_div_en_internal;
        CData/*2:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_md_state_q;
        CData/*2:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_md_state_d;
        CData/*1:0*/ ibex_core_ex_block_i_gen_mult_div_fast_q;
        CData/*1:0*/ ibex_core_ex_block_i_gen_mult_div_fast_d;
        CData/*0:0*/ ibex_core_load_store_unit_i_addr_update;
        CData/*0:0*/ ibex_core_load_store_unit_i_ctrl_update;
        CData/*0:0*/ ibex_core_load_store_unit_i_rdata_update;
        CData/*1:0*/ ibex_core_load_store_unit_i_rdata_offset_q;
        CData/*1:0*/ ibex_core_load_store_unit_i_data_type_q;
        CData/*0:0*/ ibex_core_load_store_unit_i_data_sign_ext_q;
        CData/*0:0*/ ibex_core_load_store_unit_i_data_we_q;
        CData/*3:0*/ ibex_core_load_store_unit_i_data_be;
        CData/*0:0*/ ibex_core_load_store_unit_i_split_misaligned_access;
        CData/*0:0*/ ibex_core_load_store_unit_i_handle_misaligned_q;
        CData/*0:0*/ ibex_core_load_store_unit_i_handle_misaligned_d;
        CData/*0:0*/ ibex_core_load_store_unit_i_pmp_err_q;
        CData/*0:0*/ ibex_core_load_store_unit_i_pmp_err_d;
        CData/*0:0*/ ibex_core_load_store_unit_i_lsu_err_q;
        CData/*0:0*/ ibex_core_load_store_unit_i_lsu_err_d;
        CData/*0:0*/ ibex_core_load_store_unit_i_data_or_pmp_err;
        CData/*2:0*/ ibex_core_load_store_unit_i_ls_fsm_cs;
        CData/*2:0*/ ibex_core_load_store_unit_i_ls_fsm_ns;
        CData/*1:0*/ ibex_core_wb_stage_i_rf_wdata_wb_mux_we;
        CData/*1:0*/ ibex_core_cs_reg_i_priv_lvl_q;
        CData/*1:0*/ ibex_core_cs_reg_i_priv_lvl_d;
        CData/*5:0*/ ibex_core_cs_reg_i_mstatus_d;
        CData/*0:0*/ ibex_core_cs_reg_i_mstatus_en;
        CData/*0:0*/ ibex_core_cs_reg_i_mie_en;
        CData/*0:0*/ ibex_core_cs_reg_i_mscratch_en;
        CData/*0:0*/ ibex_core_cs_reg_i_mepc_en;
        CData/*5:0*/ ibex_core_cs_reg_i_mcause_d;
        CData/*0:0*/ ibex_core_cs_reg_i_mcause_en;
        CData/*0:0*/ ibex_core_cs_reg_i_mtval_en;
        CData/*0:0*/ ibex_core_cs_reg_i_mtvec_en;
        CData/*0:0*/ ibex_core_cs_reg_i_dcsr_en;
        CData/*0:0*/ ibex_core_cs_reg_i_depc_en;
        CData/*0:0*/ ibex_core_cs_reg_i_dscratch0_en;
        CData/*0:0*/ ibex_core_cs_reg_i_dscratch1_en;
        CData/*2:0*/ ibex_core_cs_reg_i_mstack_d;
        CData/*0:0*/ ibex_core_cs_reg_i_mstack_en;
        CData/*0:0*/ ibex_core_cs_reg_i_mcountinhibit_we;
        CData/*5:0*/ ibex_core_cs_reg_i_cpuctrl_d;
    };
    struct {
        CData/*0:0*/ ibex_core_cs_reg_i_cpuctrl_we;
        CData/*0:0*/ ibex_core_cs_reg_i_csr_we_int;
        CData/*0:0*/ ibex_core_cs_reg_i_csr_wreq;
        CData/*0:0*/ ibex_core_cs_reg_i_illegal_csr;
        CData/*5:0*/ ibex_core_cs_reg_i_u_mstatus_csr__rdata_q;
        CData/*5:0*/ ibex_core_cs_reg_i_u_mcause_csr__rdata_q;
        CData/*2:0*/ ibex_core_cs_reg_i_u_mstack_csr__rdata_q;
        CData/*5:0*/ ibex_core_cs_reg_i_u_mstack_cause_csr__rdata_q;
        CData/*0:0*/ ibex_core_cs_reg_i_mcycle_counter_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_minstret_counter_i_we;
        CData/*5:0*/ ibex_core_cs_reg_i_u_cpuctrl_csr__rdata_q;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_0_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_1_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_2_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_3_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_4_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_5_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_6_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_7_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_8_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_9_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_10_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_11_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_12_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_13_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_14_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_15_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_16_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_17_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_18_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_19_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_20_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_21_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_22_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_23_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_24_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_25_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_26_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_27_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_core_cs_reg_i_cntrs_28_gen_mcnt_var_i_we;
        CData/*0:0*/ ibex_u_core_u_ibex_tracer__insn_is_compressed;
        CData/*4:0*/ ibex_u_core_u_ibex_tracer__data_accessed;
        CData/*0:0*/ ibex_u_core_u_ibex_tracer__trace_log_enable;
        CData/*2:0*/ ibex_simulator_ctrl__sim_finish;
        CData/*0:0*/ ibex_timer_timer_we;
        CData/*0:0*/ ibex_timer_mtimecmp_we;
        CData/*0:0*/ ibex_timer_mtimecmph_we;
        CData/*0:0*/ ibex_timer_interrupt_q;
        CData/*0:0*/ ibex_timer_interrupt_d;
        CData/*0:0*/ ibex_timer_error_q;
        CData/*0:0*/ ibex_timer_error_d;
        CData/*0:0*/ ibex_timer_rvalid_q;
        SData/*15:0*/ ibex_core_instr_rdata_c_id;
        SData/*11:0*/ ibex_core_csr_addr;
        SData/*15:0*/ ibex_core_ex_block_i_gen_multdiv_fast__i_gen_mult_op_a;
        SData/*15:0*/ ibex_core_ex_block_i_gen_multdiv_fast__i_gen_mult_op_b;
        IData/*31:0*/ ibex_simple_system__instr_rdata;
        IData/*31:0*/ ibex_core_instr_rdata_id;
        IData/*31:0*/ ibex_core_pc_id;
        IData/*31:0*/ ibex_core_rf_wdata_wb;
        IData/*31:0*/ ibex_core_result_ex;
        IData/*17:0*/ ibex_core_irqs;
        IData/*31:0*/ ibex_core_csr_mtval;
        IData/*31:0*/ ibex_core_rvfi_rs1_data_d;
    };
    struct {
        IData/*31:0*/ ibex_core_rvfi_rs1_data_q;
        IData/*31:0*/ ibex_core_rvfi_rs2_data_d;
        IData/*31:0*/ ibex_core_rvfi_rs2_data_q;
        IData/*31:0*/ ibex_core_rvfi_rd_wdata_d;
        IData/*31:0*/ ibex_core_rvfi_rd_wdata_q;
        IData/*31:0*/ ibex_core_rvfi_mem_rdata_d;
        IData/*31:0*/ ibex_core_rvfi_mem_rdata_q;
        IData/*31:0*/ ibex_core_rvfi_mem_wdata_d;
        IData/*31:0*/ ibex_core_rvfi_mem_wdata_q;
        IData/*31:0*/ ibex_core_rvfi_mem_addr_d;
        IData/*31:0*/ ibex_core_rvfi_mem_addr_q;
        IData/*31:0*/ ibex_core_rf_rdata_a_ecc;
        IData/*31:0*/ ibex_core_rf_rdata_b_ecc;
        IData/*31:0*/ ibex_core_if_stage_i_fetch_addr_n;
        IData/*31:0*/ ibex_core_if_stage_i_fetch_rdata;
        IData/*31:0*/ ibex_core_if_stage_i_instr_decompressed;
        IData/*31:0*/ ibex_core_pre_buf_i_stored_addr_q;
        IData/*31:0*/ ibex_core_pre_buf_i_fetch_addr_d;
        IData/*31:0*/ ibex_core_pre_buf_i_fetch_addr_q;
        IData/*31:0*/ ibex_core_pre_buf_i_instr_addr;
        WData/*95:0*/ ibex_core_pre_buf_i_fifo_i_rdata_d[3];
        WData/*95:0*/ ibex_core_pre_buf_i_fifo_i_rdata_q[3];
        IData/*31:0*/ ibex_core_pre_buf_i_fifo_i_rdata;
        IData/*30:0*/ ibex_core_pre_buf_i_fifo_i_instr_addr_d;
        IData/*30:0*/ ibex_core_pre_buf_i_fifo_i_instr_addr_q;
        IData/*31:0*/ ibex_core_id_stage_i_imm_b;
        IData/*31:0*/ ibex_core_id_stage_i_alu_operand_a;
        IData/*31:0*/ ibex_core_id_stage_i_alu_operand_b;
        IData/*31:0*/ ibex_core_ex_block_i_alu_result;
        IData/*31:0*/ ibex_core_ex_block_i_alu_i_operand_a_rev;
        IData/*31:0*/ ibex_core_ex_block_i_alu_i_shift_operand;
        IData/*31:0*/ ibex_core_ex_block_i_alu_i_shift_result;
        IData/*31:0*/ ibex_core_ex_block_i_alu_i_shift_result_rev;
        IData/*31:0*/ ibex_core_ex_block_i_alu_i_bfp_mask_rev;
        IData/*31:0*/ ibex_core_ex_block_i_alu_i_bwlogic_result;
        IData/*31:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_op_numerator_q;
        IData/*31:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_op_quotient_q;
        IData/*31:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_op_denominator_d;
        IData/*31:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_op_numerator_d;
        IData/*31:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_op_quotient_d;
        IData/*31:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_next_remainder;
        IData/*31:0*/ ibex_core_load_store_unit_i_addr_last_q;
        IData/*23:0*/ ibex_core_load_store_unit_i_rdata_q;
        IData/*31:0*/ ibex_core_load_store_unit_i_data_rdata_ext;
        IData/*31:0*/ ibex_core_load_store_unit_i_rdata_h_ext;
        IData/*31:0*/ ibex_core_load_store_unit_i_rdata_b_ext;
        IData/*31:0*/ ibex_core_cs_reg_i_exception_pc;
        IData/*17:0*/ ibex_core_cs_reg_i_mie_d;
        IData/*31:0*/ ibex_core_cs_reg_i_mepc_d;
        IData/*31:0*/ ibex_core_cs_reg_i_mtval_d;
        IData/*17:0*/ ibex_core_cs_reg_i_mip;
        IData/*31:0*/ ibex_core_cs_reg_i_dcsr_d;
        IData/*31:0*/ ibex_core_cs_reg_i_depc_d;
        IData/*31:0*/ ibex_core_cs_reg_i_mcountinhibit_d;
        IData/*31:0*/ ibex_core_cs_reg_i_mcountinhibit_q;
        IData/*31:0*/ ibex_core_cs_reg_i_mhpmcounter_we;
        IData/*31:0*/ ibex_core_cs_reg_i_mhpmcounterh_we;
        IData/*31:0*/ ibex_core_cs_reg_i_mhpmcounter_incr;
        IData/*31:0*/ ibex_core_cs_reg_i_csr_wdata_int;
        IData/*31:0*/ ibex_core_cs_reg_i_csr_rdata_int;
        IData/*31:0*/ ibex_core_cs_reg_i_u_mepc_csr__rdata_q;
        IData/*17:0*/ ibex_core_cs_reg_i_u_mie_csr__rdata_q;
        IData/*31:0*/ ibex_core_cs_reg_i_u_mscratch_csr__rdata_q;
        IData/*31:0*/ ibex_core_cs_reg_i_u_mtval_csr__rdata_q;
    };
    struct {
        IData/*31:0*/ ibex_core_cs_reg_i_u_mtvec_csr__rdata_q;
        IData/*31:0*/ ibex_core_cs_reg_i_u_dcsr_csr__rdata_q;
        IData/*31:0*/ ibex_core_cs_reg_i_u_depc_csr__rdata_q;
        IData/*31:0*/ ibex_core_cs_reg_i_u_dscratch0_csr__rdata_q;
        IData/*31:0*/ ibex_core_cs_reg_i_u_dscratch1_csr__rdata_q;
        IData/*31:0*/ ibex_core_cs_reg_i_u_mstack_epc_csr__rdata_q;
        WData/*1023:0*/ ibex_core_gen_reg_file_rf_reg[32];
        WData/*991:0*/ ibex_core_gen_reg_file_rf_reg_q[31];
        IData/*30:0*/ ibex_core_gen_reg_file_we_a_dec;
        IData/*31:0*/ ibex_u_core_u_ibex_tracer__file_handle;
        IData/*31:0*/ ibex_u_core_u_ibex_tracer__cycle;
        IData/*31:0*/ ibex_ram_a_wmask;
        IData/*31:0*/ ibex_ram_b_wmask;
        IData/*31:0*/ ibex_ram_gen_generic_impl_a_wmask;
        IData/*31:0*/ ibex_ram_gen_generic_impl_b_wmask;
        IData/*31:0*/ ibex_ram_gen_generic_impl_unnamedblk1__i;
        IData/*31:0*/ ibex_ram_gen_generic_impl_unnamedblk2__i;
        IData/*31:0*/ ibex_simulator_ctrl__log_fd;
        IData/*31:0*/ ibex_timer_mtime_wdata;
        IData/*31:0*/ ibex_timer_mtimeh_wdata;
        IData/*31:0*/ ibex_timer_mtimecmp_wdata;
        IData/*31:0*/ ibex_timer_mtimecmph_wdata;
        IData/*31:0*/ ibex_timer_rdata_q;
        IData/*31:0*/ ibex_timer_rdata_d;
        WData/*127:0*/ ibex_u_core_crash_dump_o[4];
        QData/*32:0*/ ibex_core_ex_block_i_multdiv_alu_operand_b;
        QData/*32:0*/ ibex_core_ex_block_i_multdiv_alu_operand_a;
        QData/*33:0*/ ibex_core_ex_block_i_alu_adder_result_ext;
        QData/*32:0*/ ibex_core_ex_block_i_alu_i_shift_result_ext_signed;
        QData/*32:0*/ ibex_core_ex_block_i_alu_i_shift_result_ext;
        QData/*33:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_accum;
        QData/*33:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_mac_res_d;
        QData/*33:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_op_remainder_d;
        QData/*32:0*/ ibex_core_ex_block_i_gen_multdiv_fast_i_next_quotient;
        QData/*63:0*/ ibex_core_cs_reg_i_mcycle_counter_i_counter_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_mcycle_counter_i_counter_load;
        QData/*63:0*/ ibex_core_cs_reg_i_mcycle_counter_i_counter_d;
        QData/*63:0*/ ibex_core_cs_reg_i_mcycle_counter_i_counter_q;
        QData/*63:0*/ ibex_core_cs_reg_i_minstret_counter_i_counter_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_minstret_counter_i_counter_load;
        QData/*63:0*/ ibex_core_cs_reg_i_minstret_counter_i_counter_d;
        QData/*63:0*/ ibex_core_cs_reg_i_minstret_counter_i_counter_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_0_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_0_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_0_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_0_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_0_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_1_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_1_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_1_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_1_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_1_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_2_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_2_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_2_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_2_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_2_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_3_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_3_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_3_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_3_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_3_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_4_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_4_var_cnt_upd;
    };
    struct {
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_4_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_4_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_4_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_5_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_5_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_5_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_5_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_5_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_6_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_6_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_6_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_6_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_6_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_7_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_7_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_7_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_7_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_7_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_8_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_8_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_8_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_8_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_8_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_9_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_9_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_9_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_9_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_9_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_10_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_10_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_10_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_10_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_10_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_11_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_11_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_11_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_11_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_11_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_12_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_12_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_12_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_12_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_12_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_13_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_13_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_13_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_13_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_13_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_14_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_14_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_14_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_14_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_14_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_15_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_15_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_15_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_15_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_15_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_16_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_16_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_16_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_16_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_16_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_17_var_cnt;
    };
    struct {
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_17_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_17_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_17_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_17_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_18_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_18_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_18_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_18_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_18_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_19_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_19_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_19_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_19_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_19_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_20_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_20_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_20_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_20_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_20_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_21_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_21_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_21_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_21_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_21_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_22_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_22_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_22_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_22_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_22_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_23_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_23_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_23_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_23_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_23_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_24_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_24_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_24_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_24_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_24_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_25_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_25_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_25_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_25_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_25_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_26_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_26_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_26_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_26_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_26_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_27_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_27_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_27_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_27_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_27_var_cnt_q;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_28_var_cnt;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_28_var_cnt_upd;
        QData/*63:0*/ ibex_core_cs_reg_i_cntrs_28_var_cnt_load;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_28_var_cnt_d;
        QData/*39:0*/ ibex_core_cs_reg_i_cntrs_28_var_cnt_q;
        QData/*63:0*/ ibex_timer_mtime_q;
        QData/*63:0*/ ibex_timer_mtime_d;
        QData/*63:0*/ ibex_timer_mtimecmp_q;
        QData/*63:0*/ ibex_timer_mtimecmp_d;
        CData/*0:0*/ ibex_simple_system__host_req[1];
    };
    struct {
        CData/*0:0*/ ibex_simple_system__host_gnt[1];
        IData/*31:0*/ ibex_simple_system__host_addr[1];
        CData/*0:0*/ ibex_simple_system__host_we[1];
        CData/*3:0*/ ibex_simple_system__host_be[1];
        IData/*31:0*/ ibex_simple_system__host_wdata[1];
        CData/*0:0*/ ibex_simple_system__host_rvalid[1];
        IData/*31:0*/ ibex_simple_system__host_rdata[1];
        CData/*0:0*/ ibex_simple_system__host_err[1];
        CData/*0:0*/ ibex_device_req[3];
        IData/*31:0*/ ibex_device_addr[3];
        CData/*0:0*/ ibex_device_we[3];
        CData/*3:0*/ ibex_device_be[3];
        IData/*31:0*/ ibex_device_wdata[3];
        CData/*0:0*/ ibex_device_rvalid[3];
        IData/*31:0*/ ibex_device_rdata[3];
        CData/*0:0*/ ibex_device_err[3];
        IData/*31:0*/ ibex_simple_system__cfg_device_addr_base[3];
        IData/*31:0*/ ibex_simple_system__cfg_device_addr_mask[3];
        QData/*33:0*/ ibex_core_imd_val_d_ex[2];
        QData/*33:0*/ ibex_core_imd_val_q_ex[2];
        QData/*33:0*/ ibex_core_csr_pmp_addr[4];
        CData/*5:0*/ ibex_core_csr_pmp_cfg[4];
        CData/*0:0*/ ibex_core_pmp_req_err[2];
        CData/*0:0*/ ibex_core_rvfi_stage_valid[1];
        QData/*63:0*/ ibex_core_rvfi_stage_order[1];
        IData/*31:0*/ ibex_core_rvfi_stage_insn[1];
        CData/*0:0*/ ibex_core_rvfi_stage_trap[1];
        CData/*0:0*/ ibex_core_rvfi_stage_halt[1];
        CData/*0:0*/ ibex_core_rvfi_stage_intr[1];
        CData/*1:0*/ ibex_core_rvfi_stage_mode[1];
        CData/*1:0*/ ibex_core_rvfi_stage_ixl[1];
        CData/*4:0*/ ibex_core_rvfi_stage_rs1_addr[1];
        CData/*4:0*/ ibex_core_rvfi_stage_rs2_addr[1];
        CData/*4:0*/ ibex_core_rvfi_stage_rs3_addr[1];
        IData/*31:0*/ ibex_core_rvfi_stage_rs1_rdata[1];
        IData/*31:0*/ ibex_core_rvfi_stage_rs2_rdata[1];
        IData/*31:0*/ ibex_core_rvfi_stage_rs3_rdata[1];
        CData/*4:0*/ ibex_core_rvfi_stage_rd_addr[1];
        IData/*31:0*/ ibex_core_rvfi_stage_rd_wdata[1];
        IData/*31:0*/ ibex_core_rvfi_stage_pc_rdata[1];
        IData/*31:0*/ ibex_core_rvfi_stage_pc_wdata[1];
        IData/*31:0*/ ibex_core_rvfi_stage_mem_addr[1];
        CData/*3:0*/ ibex_core_rvfi_stage_mem_rmask[1];
        CData/*3:0*/ ibex_core_rvfi_stage_mem_wmask[1];
        IData/*31:0*/ ibex_core_rvfi_stage_mem_rdata[1];
        IData/*31:0*/ ibex_core_rvfi_stage_mem_wdata[1];
        CData/*0:0*/ ibex_core_rvfi_stage_valid_d[1];
        QData/*33:0*/ ibex_core_g_no_pmp__unused_csr_pmp_addr[4];
        CData/*5:0*/ ibex_core_g_no_pmp__unused_csr_pmp_cfg[4];
        QData/*33:0*/ ibex_core_id_stage_i_imd_val_q[2];
        IData/*31:0*/ ibex_core_ex_block_i_alu_imd_val_q[2];
        IData/*31:0*/ ibex_core_ex_block_i_alu_imd_val_d[2];
        QData/*33:0*/ ibex_core_ex_block_i_multdiv_imd_val_d[2];
        IData/*31:0*/ ibex_core_ex_block_i_alu_i_g_no_alu_rvb__unused_imd_val_q[2];
        IData/*31:0*/ ibex_core_wb_stage_i_rf_wdata_wb_mux[2];
        IData/*31:0*/ ibex_core_cs_reg_i_pmp_addr_rdata[16];
        CData/*7:0*/ ibex_core_cs_reg_i_pmp_cfg_rdata[16];
        QData/*63:0*/ ibex_core_cs_reg_i_mhpmcounter[32];
        IData/*31:0*/ ibex_core_cs_reg_i_mhpmevent[32];
        IData/*31:0*/ ibex_ram_gen_generic_impl_mem[262144];
    };
    std::string ibex_u_core_u_ibex_tracer__file_name;
    std::string ibex_u_core_u_ibex_tracer__decoded_str;
    
    // LOCAL VARIABLES
    // Internals; generally not touched by application code
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ ibex_Vcellout__u_ram__a_rvalid_o;
        CData/*0:0*/ ibex_Vcellout__u_simulator_ctrl__rvalid_o;
        CData/*0:0*/ ibex_bus___Vlvbound1;
        CData/*0:0*/ ibex_bus___Vlvbound2;
        CData/*3:0*/ ibex_bus___Vlvbound5;
        CData/*0:0*/ ibex_bus___Vlvbound12;
        CData/*0:0*/ ibex_bus___Vlvbound13;
        CData/*0:0*/ ibex_bus___Vlvbound18;
        CData/*0:0*/ ibex_core_gen_reg_file___Vlvbound1;
        CData/*7:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__11__imm;
        CData/*7:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_compressed_store_insn__14__imm;
        CData/*7:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__15__imm;
        CData/*7:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_compressed_store_insn__16__imm;
        CData/*7:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__22__imm;
        CData/*5:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_sr_insn__25__shamt;
        CData/*5:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_sr_insn__28__shamt;
        CData/*7:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__43__imm;
        CData/*5:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_sr_insn__46__shamt;
        CData/*5:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_sr_insn__49__shamt;
        CData/*5:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_ci_clui_insn__53__nzimm;
        CData/*7:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_compressed_load_insn__56__imm;
        CData/*5:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_ci_cli_insn__57__imm;
        CData/*7:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_compressed_load_insn__58__imm;
        CData/*5:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_ci_cslli_insn__63__shamt;
        CData/*5:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_ci_caddi_insn__64__nzimm;
        CData/*4:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_i_shift_insn__84__shamt;
        CData/*4:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_i_shift_insn__85__shamt;
        CData/*4:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_i_shift_insn__86__shamt;
        CData/*2:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_load_insn__122__size;
        CData/*3:0*/ __Vfunc_ibex_u_core_u_ibex_tracer__get_fence_description__128__bits;
        CData/*3:0*/ __Vfunc_ibex_u_core_u_ibex_tracer__get_fence_description__129__bits;
        CData/*4:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_i_shift_insn__131__shamt;
        CData/*4:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_i_shift_insn__132__shamt;
        CData/*4:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_i_shift_insn__133__shamt;
        CData/*5:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_i_funnelshift_insn__225__shamt;
        CData/*5:0*/ __Vtableidx1;
        CData/*5:0*/ __Vtableidx2;
        CData/*5:0*/ __Vtableidx3;
        CData/*7:0*/ __Vtableidx4;
        CData/*5:0*/ __Vtableidx5;
        CData/*4:0*/ __Vtableidx6;
        CData/*0:0*/ __Vclklast__TOP__IO_RST_N;
        CData/*0:0*/ __Vclklast__TOP__ibex_simple_system__clk_sys;
        CData/*0:0*/ __Vclklast__TOP__ibex_core_clk;
        SData/*9:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_ci_caddi16sp_insn__52__nzimm;
        SData/*9:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_ciw_insn__66__nzuimm;
        SData/*11:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__97__csr;
        SData/*11:0*/ __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__98__csr_addr;
        SData/*11:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__99__csr;
        SData/*11:0*/ __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__100__csr_addr;
        SData/*11:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__101__csr;
        SData/*11:0*/ __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__102__csr_addr;
        SData/*11:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__103__csr;
        SData/*11:0*/ __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__104__csr_addr;
        SData/*11:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__105__csr;
        SData/*11:0*/ __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__106__csr_addr;
        SData/*11:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__107__csr;
        SData/*11:0*/ __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__108__csr_addr;
        IData/*31:0*/ ibex_Vcellout__u_ram__a_rdata_o;
        IData/*31:0*/ ibex_bus___Vlvbound3;
        IData/*31:0*/ ibex_bus___Vlvbound4;
        IData/*31:0*/ ibex_bus___Vlvbound14;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__11__jump_target;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__15__jump_target;
    };
    struct {
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__22__jump_target;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__43__jump_target;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__71__branch_target;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__71__imm;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__72__branch_target;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__72__imm;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__73__branch_target;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__73__imm;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__74__branch_target;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__74__imm;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__75__branch_target;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__75__imm;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__76__branch_target;
        IData/*31:0*/ __Vtask_ibex_u_core_u_ibex_tracer__decode_b_insn__76__imm;
        IData/*31:0*/ __Vdly__ibex_u_core_u_ibex_tracer__cycle;
        IData/*31:0*/ ibex_Vcellinp_u_bus__cfg_device_addr_mask[3];
        IData/*31:0*/ ibex_Vcellinp_u_bus__cfg_device_addr_base[3];
        CData/*0:0*/ ibex_Vcellinp_u_bus__device_err_i[3];
        IData/*31:0*/ ibex_Vcellinp_u_bus__device_rdata_i[3];
        CData/*0:0*/ ibex_Vcellinp_u_bus__device_rvalid_i[3];
        IData/*31:0*/ ibex_Vcellout__u_bus__device_wdata_o[3];
        CData/*3:0*/ ibex_Vcellout__u_bus__device_be_o[3];
        CData/*0:0*/ ibex_Vcellout__u_bus__device_we_o[3];
        IData/*31:0*/ ibex_Vcellout__u_bus__device_addr_o[3];
        CData/*0:0*/ ibex_Vcellout__u_bus__device_req_o[3];
        CData/*0:0*/ ibex_Vcellout__u_bus__host_err_o[1];
        IData/*31:0*/ ibex_Vcellout__u_bus__host_rdata_o[1];
        CData/*0:0*/ ibex_Vcellout__u_bus__host_rvalid_o[1];
        IData/*31:0*/ ibex_Vcellinp_u_bus__host_wdata_i[1];
        CData/*3:0*/ ibex_Vcellinp_u_bus__host_be_i[1];
        CData/*0:0*/ ibex_Vcellinp_u_bus__host_we_i[1];
        IData/*31:0*/ ibex_Vcellinp_u_bus__host_addr_i[1];
        CData/*0:0*/ ibex_Vcellout__u_bus__host_gnt_o[1];
        CData/*0:0*/ ibex_Vcellinp_u_bus__host_req_i[1];
        QData/*33:0*/ ibex_core___Vcellinp__id_stage_i__imd_val_d_ex_i[2];
        QData/*33:0*/ ibex_core___Vcellout__id_stage_i__imd_val_q_ex_o[2];
        QData/*33:0*/ ibex_core___Vcellinp__ex_block_i__imd_val_q_i[2];
        QData/*33:0*/ ibex_core___Vcellout__ex_block_i__imd_val_d_o[2];
        QData/*33:0*/ ibex_core___Vcellout__cs_reg_i__csr_pmp_addr_o[4];
        CData/*5:0*/ ibex_core___Vcellout__cs_reg_i__csr_pmp_cfg_o[4];
        IData/*31:0*/ ibex_core_ex_block_i___Vcellout__alu_i__imd_val_d_o[2];
        IData/*31:0*/ ibex_core_ex_block_i___Vcellinp__alu_i__imd_val_q_i[2];
        QData/*33:0*/ ibex_core_ex_block_i___Vcellout__gen_multdiv_fast_i__imd_val_d_o[2];
        QData/*33:0*/ ibex_core_ex_block_i___Vcellinp__gen_multdiv_fast_i__imd_val_q_i[2];
        CData/*0:0*/ __Vm_traceActivity[11];
    };
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_cr_insn__6__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_cr_insn__7__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_cr_insn__8__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_cr_insn__9__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__11__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__15__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__22__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_cb_insn__43__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__97__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__97__csr_name;
    std::string __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__98__Vfuncout;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__99__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__99__csr_name;
    std::string __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__100__Vfuncout;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__101__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__101__csr_name;
    std::string __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__102__Vfuncout;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__103__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__103__csr_name;
    std::string __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__104__Vfuncout;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__105__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__105__csr_name;
    std::string __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__106__Vfuncout;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__107__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_csr_insn__107__csr_name;
    std::string __Vfunc_ibex_u_core_u_ibex_tracer__get_csr_name__108__Vfuncout;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_load_insn__122__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_mnemonic__123__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_store_insn__124__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_mnemonic__125__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_mnemonic__126__mnemonic;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_fence__127__predecessor;
    std::string __Vtask_ibex_u_core_u_ibex_tracer__decode_fence__127__successor;
    std::string __Vfunc_ibex_u_core_u_ibex_tracer__get_fence_description__128__Vfuncout;
    std::string __Vfunc_ibex_u_core_u_ibex_tracer__get_fence_description__128__desc;
    std::string __Vfunc_ibex_u_core_u_ibex_tracer__get_fence_description__129__Vfuncout;
    std::string __Vfunc_ibex_u_core_u_ibex_tracer__get_fence_description__129__desc;
    static CData/*0:0*/ __Vtable1_ibex_core_id_stage_i_controller_i_instr_fetch_err_prio[64];
    static CData/*0:0*/ __Vtable1_ibex_core_id_stage_i_controller_i_illegal_insn_prio[64];
    static CData/*0:0*/ __Vtable1_ibex_core_id_stage_i_controller_i_ecall_insn_prio[64];
    static CData/*0:0*/ __Vtable1_ibex_core_id_stage_i_controller_i_ebrk_insn_prio[64];
    static CData/*0:0*/ __Vtable1_ibex_core_id_stage_i_controller_i_store_err_prio[64];
    static CData/*0:0*/ __Vtable1_ibex_core_id_stage_i_controller_i_load_err_prio[64];
    static CData/*0:0*/ __Vtable2_ibex_core_ex_block_i_alu_i_adder_op_b_negate[64];
    static CData/*0:0*/ __Vtable3_ibex_core_ex_block_i_alu_i_cmp_signed[64];
    static CData/*0:0*/ __Vtable4_ibex_core_ex_block_i_alu_i_cmp_result[256];
    static CData/*0:0*/ __Vtable5_ibex_core_ex_block_i_alu_i_shift_left[64];
    static CData/*3:0*/ __Vtable6_ibex_core_load_store_unit_i_data_be[32];
    
    // INTERNAL VARIABLES
    // Internals; generally not touched by application code
    Vibex_simple_system__Syms* __VlSymsp;  // Symbol table
    
    // CONSTRUCTORS
  private:
    VL_UNCOPYABLE(Vibex_simple_system);  ///< Copying not allowed
  public:
    /// Construct the model; called by application code
    /// The special name  may be used to make a wrapper with a
    /// single model invisible with respect to DPI scope names.
    Vibex_simple_system(const char* name = "TOP");
    /// Destroy the model; called (often implicitly) by application code
    ~Vibex_simple_system();
    /// Trace signals in the model; called by application code
    void trace(VerilatedFstC* tfp, int levels, int options = 0);
    
    // API METHODS
    /// Evaluate the model.  Application must call when inputs change.
    void eval() { eval_step(); }
    /// Evaluate when calling multiple units/models per time step.
    void eval_step();
    /// Evaluate at end of a timestep for tracing, when using eval_step().
    /// Application must call after all eval() and before time changes.
    void eval_end_step() {}
    /// Simulation complete, run final blocks.  Application must call on completion.
    void final();
    
    // INTERNAL METHODS
    static void _eval_initial_loop(Vibex_simple_system__Syms* __restrict vlSymsp);
    void __Vconfigure(Vibex_simple_system__Syms* symsp, bool first);
    static void __Vdpiexp_ibex_simple_system__mhpmcounter_get_TOP(Vibex_simple_system__Syms* __restrict vlSymsp, IData/*31:0*/ index, QData/*63:0*/ (&mhpmcounter_get__Vfuncrtn));
    static void __Vdpiexp_ibex_ram_gen_generic_impl_simutil_get_mem_TOP(Vibex_simple_system__Syms* __restrict vlSymsp, IData/*31:0*/ index, WData/*311:0*/ (&val)[10], IData/*31:0*/ (&simutil_get_mem__Vfuncrtn));
    static void __Vdpiexp_ibex_ram_gen_generic_impl_simutil_memload_TOP(Vibex_simple_system__Syms* __restrict vlSymsp, std::string file);
    static void __Vdpiexp_ibex_ram_gen_generic_impl_simutil_set_mem_TOP(Vibex_simple_system__Syms* __restrict vlSymsp, IData/*31:0*/ index, WData/*311:0*/ val[10], IData/*31:0*/ (&simutil_set_mem__Vfuncrtn));
  private:
    static QData _change_request(Vibex_simple_system__Syms* __restrict vlSymsp);
    static QData _change_request_1(Vibex_simple_system__Syms* __restrict vlSymsp);
  public:
    static void _combo__TOP__17(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _combo__TOP__4(Vibex_simple_system__Syms* __restrict vlSymsp);
  private:
    void _ctor_var_reset() VL_ATTR_COLD;
  public:
    static void _eval(Vibex_simple_system__Syms* __restrict vlSymsp);
  private:
#ifdef VL_DEBUG
    void _eval_debug_assertions();
#endif  // VL_DEBUG
  public:
    static void _eval_initial(Vibex_simple_system__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _eval_settle(Vibex_simple_system__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _final_TOP(Vibex_simple_system__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _initial__TOP__3(Vibex_simple_system__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _multiclk__TOP__15(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _multiclk__TOP__18(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _sequent__TOP__10(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _sequent__TOP__11(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _sequent__TOP__12(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _sequent__TOP__13(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _sequent__TOP__14(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _sequent__TOP__16(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _sequent__TOP__6(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _sequent__TOP__7(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _sequent__TOP__8(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _sequent__TOP__9(Vibex_simple_system__Syms* __restrict vlSymsp);
    static void _settle__TOP__1(Vibex_simple_system__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__2(Vibex_simple_system__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static void _settle__TOP__5(Vibex_simple_system__Syms* __restrict vlSymsp) VL_ATTR_COLD;
    static unsigned long long mhpmcounter_get(int index);
    static int simutil_get_mem(int index, svBitVecVal* val);
    static void simutil_memload(const char* file);
    static int simutil_set_mem(int index, const svBitVecVal* val);
  private:
    static void traceChgSub0(void* userp, VerilatedFst* tracep);
    static void traceChgTop0(void* userp, VerilatedFst* tracep);
    static void traceCleanup(void* userp, VerilatedFst* /*unused*/);
    static void traceFullSub0(void* userp, VerilatedFst* tracep) VL_ATTR_COLD;
    static void traceFullTop0(void* userp, VerilatedFst* tracep) VL_ATTR_COLD;
    static void traceInitSub0(void* userp, VerilatedFst* tracep) VL_ATTR_COLD;
    static void traceInitTop(void* userp, VerilatedFst* tracep) VL_ATTR_COLD;
    void traceRegister(VerilatedFst* tracep) VL_ATTR_COLD;
    static void traceInit(void* userp, VerilatedFst* tracep, uint32_t code) VL_ATTR_COLD;
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);

//----------


#endif  // guard
