
/* autogenerated - do not edit */
#include "jim.h"
#include "jimautoconf.h"
int Jim_InitStaticExtensions(Jim_Interp *interp)

{
	extern int Jim_stdlibInit(Jim_Interp *);
	extern int Jim_arrayInit(Jim_Interp *);
	extern int Jim_clockInit(Jim_Interp *);
	extern int Jim_eventloopInit(Jim_Interp *);
	extern int Jim_regexpInit(Jim_Interp *);
	extern int Jim_tclcompatInit(Jim_Interp *);
	Jim_stdlibInit(interp);
	Jim_arrayInit(interp);
	Jim_clockInit(interp);
	Jim_eventloopInit(interp);
	Jim_regexpInit(interp);
	Jim_tclcompatInit(interp);
	return JIM_OK;
}
