/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "qemu/module.h"
#include "trace.h"

uint16_t _TRACE_SIFIVE_GPIO_READ_DSTATE;
uint16_t _TRACE_SIFIVE_GPIO_WRITE_DSTATE;
uint16_t _TRACE_SIFIVE_GPIO_SET_DSTATE;
uint16_t _TRACE_SIFIVE_GPIO_UPDATE_OUTPUT_IRQ_DSTATE;
TraceEvent _TRACE_SIFIVE_GPIO_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sifive_gpio_read",
    .sstate = TRACE_SIFIVE_GPIO_READ_ENABLED,
    .dstate = &_TRACE_SIFIVE_GPIO_READ_DSTATE 
};
TraceEvent _TRACE_SIFIVE_GPIO_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sifive_gpio_write",
    .sstate = TRACE_SIFIVE_GPIO_WRITE_ENABLED,
    .dstate = &_TRACE_SIFIVE_GPIO_WRITE_DSTATE 
};
TraceEvent _TRACE_SIFIVE_GPIO_SET_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sifive_gpio_set",
    .sstate = TRACE_SIFIVE_GPIO_SET_ENABLED,
    .dstate = &_TRACE_SIFIVE_GPIO_SET_DSTATE 
};
TraceEvent _TRACE_SIFIVE_GPIO_UPDATE_OUTPUT_IRQ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sifive_gpio_update_output_irq",
    .sstate = TRACE_SIFIVE_GPIO_UPDATE_OUTPUT_IRQ_ENABLED,
    .dstate = &_TRACE_SIFIVE_GPIO_UPDATE_OUTPUT_IRQ_DSTATE 
};
TraceEvent *hw_riscv_trace_events[] = {
    &_TRACE_SIFIVE_GPIO_READ_EVENT,
    &_TRACE_SIFIVE_GPIO_WRITE_EVENT,
    &_TRACE_SIFIVE_GPIO_SET_EVENT,
    &_TRACE_SIFIVE_GPIO_UPDATE_OUTPUT_IRQ_EVENT,
  NULL,
};

static void trace_hw_riscv_register_events(void)
{
    trace_event_register_group(hw_riscv_trace_events);
}
trace_init(trace_hw_riscv_register_events)
